#!/bin/bash

#this file is in the public domain
cd "$( dirname "${BASH_SOURCE[0]}" )"
cd ./svg

test="x$(command -v "convert")x"
if [[ $test = "xx" ]]; then
	echo "imagemagick convert utility missing, aborting."
else
	echo "imagemagick convert is installed. continuing"
	for filename in $(find . -regex ".*.svg"); do
		newfilename=`echo $filename | cut -c 3- | awk -F . '{print $1}'`
		newfilename=${filename%????}
		echo ${newfilename:2}
		convert -background "#FFFFFF66" $filename ../png/$newfilename.png
		echo "wrote ${newfilename}.png"
	done
fi
