#!/bin/bash

#this file is in the public domain
cd ./svg

test="x$(command -v "convert")x"
if [[ $test = "xx" ]]; then
	echo "imagemagick convert utility missing, aborting."
else
	echo "imagemagick convert is installed. continuing"
	for filename in $(find . -regex ".*.svg"); do
		newfilename=`echo $filename | cut -c 3- | awk -F . '{print $1}'`
		convert -background none $filename ../png/$newfilename.png
		echo "wrote ${newfilename}.png"
	done
fi
